### ISSUE TITLE
Error: The new account_id test.sync can't be created by test.near

### ISSUE THREAD

**Issue by barbaraliau** [nearprotocol/near-web3-provider#40]
Getting this error when running tests, on several branches.

@bowenwang1996 Do you know why I wouldn't be able to create an account? Not sure how to go about troubleshooting this.

`nearcore` version: `commit df431768f95bc4117dc7c4d954e38f1b96fd3b9f (HEAD -> stable, tag: stable-2020-07-13, origin/stable)`

```
console.warn
        Failure [test.sync]: Error: The new account_id test.sync can't be created by test.near

      155 |                 try {
      156 |                     const keyPair = await nearlib.KeyPair.fromRandom('ed25519');
    > 157 |                     const newAccount = await web._provider.account.createAccount('test.sync', keyPair.getPublicKey(), 2);
          |                                        ^
      158 |                     expect(newAccount).toBe('object');
      159 | 
      160 |                     const sync = await web.eth.isSyncing();

      at Account.printLogsAndFailures (node_modules/near-api-js/lib/account.js:62:25)
      at Account.signAndSendTransaction (node_modules/near-api-js/lib/account.js:137:14)
      at test/near_provider.test.js:157:40
```

**Comment by barbaraliau** [comment]
This error has disappeared. Not sure why or how. Closing issue as unable to duplicate.
